name: Playwright Tests

on:
  push:                 # Run on every push
    branches: [ "**" ]  # Any branch
  pull_request:         # Run on PRs
  workflow_dispatch:    # Allow manual run from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run Playwright test script
        run: python test_site.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            homepage.png
            iana.png
